#!/usr/bin/env python3
"""Generate deterministic Python client endpoint constants from OpenAPI specs."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

from backend.control_plane.app import create_app
from backend.gateway.app import create_gateway_app
from backend.shared_domain.config import Settings


OUTPUT_FILE = Path("sdk/python/schemapilot_client/generated_endpoints.py")


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Check that generated client artifacts are up-to-date without writing.",
    )
    return parser.parse_args()


def render_generated_endpoints(root: Path) -> str:
    specs: dict[str, list[str]] = {}
    for name, payload in _generate_current_openapi_specs().items():
        paths = payload.get("paths", {})
        if not isinstance(paths, dict):
            specs[name] = []
            continue
        specs[name] = sorted(str(item) for item in paths.keys())
    fingerprint = hashlib.sha256(
        json.dumps(specs, sort_keys=True).encode("utf-8")
    ).hexdigest()
    lines = [
        '"""Generated endpoint constants from OpenAPI baselines."""',
        "",
        "# Generated by tools/generate_clients.py; do not edit manually.",
        f'OPENAPI_FINGERPRINT = "{fingerprint}"',
        f"CONTROL_PLANE_PATHS = {json.dumps(specs['control_plane'], indent=2)}",
        f"GATEWAY_PATHS = {json.dumps(specs['gateway'], indent=2)}",
        "",
    ]
    return "\n".join(lines)


def _default_settings() -> Settings:
    return Settings(
        profile="starter",
        bind_address="127.0.0.1",
        auth_mode="local",
        require_auth_for_non_local=True,
        storage_root="./runtime/storage",
        database_url="sqlite:///./runtime/client_sdk_gen.db",
    )


def _generate_current_openapi_specs() -> dict[str, dict[str, object]]:
    control_plane = create_app(settings_factory=_default_settings)
    gateway = create_gateway_app(settings_factory=_default_settings)
    return {
        "control_plane": control_plane.openapi(),
        "gateway": gateway.openapi(),
    }


def main() -> int:
    args = _parse_args()
    root = Path(__file__).resolve().parents[1]
    content = render_generated_endpoints(root)
    output = root / OUTPUT_FILE
    if args.check:
        if not output.exists():
            print(f"FAIL generated file missing: {output.as_posix()}")
            return 1
        current = output.read_text(encoding="utf-8")
        if current != content:
            print(f"FAIL generated file out of date: {output.as_posix()}")
            return 1
        print("PASS CHK-CLIENT-SDK-GEN")
        return 0
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(content, encoding="utf-8")
    print(f"PASS generated {output.as_posix()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
