"""Generated endpoint constants from OpenAPI baselines."""

# Generated by tools/generate_clients.py; do not edit manually.
OPENAPI_FINGERPRINT = "78c6bbb8a785730daba1d8c18faa7f9194009b0292c40d544432f7ceaad96a3e"
CONTROL_PLANE_PATHS = [
  "/api/v1/health",
  "/api/v1/metrics",
  "/api/v1/onboarding/demo_bootstrap",
  "/api/v1/policy-packs",
  "/api/v1/workspaces",
  "/api/v1/workspaces/{workspace_id}",
  "/api/v1/workspaces/{workspace_id}/builds/{build_id}/publish",
  "/api/v1/workspaces/{workspace_id}/builds/{build_id}/rollback",
  "/api/v1/workspaces/{workspace_id}/catalog/export",
  "/api/v1/workspaces/{workspace_id}/catalog/import",
  "/api/v1/workspaces/{workspace_id}/datasets",
  "/api/v1/workspaces/{workspace_id}/datasets/{dataset_id}",
  "/api/v1/workspaces/{workspace_id}/deletions",
  "/api/v1/workspaces/{workspace_id}/deletions/{deletion_request_id}",
  "/api/v1/workspaces/{workspace_id}/deletions/{deletion_request_id}/approve",
  "/api/v1/workspaces/{workspace_id}/deletions/{deletion_request_id}/execute",
  "/api/v1/workspaces/{workspace_id}/evidence/{evidence_id}",
  "/api/v1/workspaces/{workspace_id}/lineage/sql",
  "/api/v1/workspaces/{workspace_id}/policy-pack",
  "/api/v1/workspaces/{workspace_id}/policy-pack/change-request",
  "/api/v1/workspaces/{workspace_id}/policy-pack/change-requests/{change_request_id}/decision",
  "/api/v1/workspaces/{workspace_id}/policy-pack/rollback",
  "/api/v1/workspaces/{workspace_id}/proposals",
  "/api/v1/workspaces/{workspace_id}/recommendations",
  "/api/v1/workspaces/{workspace_id}/recommendations/{report_id}",
  "/api/v1/workspaces/{workspace_id}/retention/policy",
  "/api/v1/workspaces/{workspace_id}/retention/purge",
  "/api/v1/workspaces/{workspace_id}/review_tasks",
  "/api/v1/workspaces/{workspace_id}/review_tasks/summary",
  "/api/v1/workspaces/{workspace_id}/review_tasks/{task_id}/decision",
  "/api/v1/workspaces/{workspace_id}/run-schedules",
  "/api/v1/workspaces/{workspace_id}/runs",
  "/api/v1/workspaces/{workspace_id}/runs/{run_id}",
  "/api/v1/workspaces/{workspace_id}/semantic-manifest",
  "/api/v1/workspaces/{workspace_id}/semantic-manifest/change-request",
  "/api/v1/workspaces/{workspace_id}/semantic-manifest/change-requests/{change_request_id}/decision",
  "/api/v1/workspaces/{workspace_id}/semantic-manifest/rollback",
  "/api/v1/workspaces/{workspace_id}/source-slas",
  "/api/v1/workspaces/{workspace_id}/source-slas/evaluate",
  "/api/v1/workspaces/{workspace_id}/sources",
  "/api/v1/workspaces/{workspace_id}/sources/{source_id}"
]
GATEWAY_PATHS = [
  "/api/v1/gateway/policy/simulate",
  "/api/v1/gateway/query",
  "/api/v1/gateway/retrieve",
  "/api/v1/health",
  "/api/v1/metrics"
]
