"""Deterministic first-hour demo scenario generator."""

from __future__ import annotations

import csv
import json
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class DemoScenarioResult:
    """Paths generated by the demo scenario helper."""

    root_path: str
    exports_path: str
    documents_path: str
    manifest_path: str
    file_count: int

    def to_dict(self) -> dict[str, object]:
        return {
            "root_path": self.root_path,
            "exports_path": self.exports_path,
            "documents_path": self.documents_path,
            "manifest_path": self.manifest_path,
            "file_count": self.file_count,
        }


def generate_demo_scenario(*, output_root: str) -> DemoScenarioResult:
    """Generate deterministic local demo data for first-hour onboarding."""
    root = Path(output_root).resolve()
    exports = root / "exports"
    documents = root / "documents"
    exports.mkdir(parents=True, exist_ok=True)
    documents.mkdir(parents=True, exist_ok=True)

    invoices_rows = [
        {"invoice_id": "INV-001", "customer_id": "C-001", "amount": "120.50", "currency": "EUR"},
        {"invoice_id": "INV-002", "customer_id": "C-002", "amount": "89.99", "currency": "USD"},
        {"invoice_id": "INV-003", "customer_id": "C-001", "amount": "42.00", "currency": "EUR"},
    ]
    customers_rows = [
        {"customer_id": "C-001", "name": "Acme GmbH", "region": "eu"},
        {"customer_id": "C-002", "name": "Northwind LLC", "region": "us"},
    ]
    tickets_rows = [
        {"ticket_id": "T-100", "customer_id": "C-001", "status": "open"},
        {"ticket_id": "T-101", "customer_id": "C-002", "status": "closed"},
    ]

    _write_csv(exports / "invoices.csv", rows=invoices_rows)
    _write_csv(exports / "customers.csv", rows=customers_rows)
    _write_csv(exports / "tickets.csv", rows=tickets_rows)
    (documents / "faq.txt").write_text(
        "Invoice INV-001 was approved by finance.\nUse customer_id for joins.\n",
        encoding="utf-8",
    )
    (documents / "runbook_note.txt").write_text(
        "This deterministic dataset is generated by SchemaPilot demo tooling.\n",
        encoding="utf-8",
    )

    manifest = {
        "scenario_version": "v1",
        "exports": sorted(path.name for path in exports.glob("*.csv")),
        "documents": sorted(path.name for path in documents.glob("*.txt")),
    }
    manifest_path = root / "manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2, sort_keys=True), encoding="utf-8")

    return DemoScenarioResult(
        root_path=root.as_posix(),
        exports_path=exports.as_posix(),
        documents_path=documents.as_posix(),
        manifest_path=manifest_path.as_posix(),
        file_count=len(manifest["exports"]) + len(manifest["documents"]) + 1,
    )


def _write_csv(path: Path, *, rows: list[dict[str, str]]) -> None:
    if not rows:
        raise ValueError("demo_rows_required")
    fieldnames = list(rows[0].keys())
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow(row)
